Create Database If Not Exists demo Character Set UTF8;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL C OMMENT '主键ID',
	username VARCHAR(50) NULL DEFAULT NULL COMMENT '姓名',
	password VARCHAR(50) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	status VARCHAR(10) NULL DEFAULT NULL COMMENT '状态',
	PRIMARY KEY (id)
);